name: Update README
on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 9 * * 1"  # segundas 06:00 BRT aprox (09:00 UTC)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate README
        run: bash scripts/generate_readme.sh
      - name: Commit changes
        run: |
          if ! git diff --quiet README.md; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-update README"
            git push
          fi
